import { cloneDeep, keys } from 'lodash';
import Mock from 'mockjs';

export const DEFAULT_NAME = 'Umi Max';

export const COLORS: any = {
  超危: '#9E0000',
  高危: '#E95454',
  中危: '#FF8A34',
  低危: '#FFC423',
  无风险: '#7F8EA8',
  建议: '#7F8EA8',
  在线: '#2177D1',
  离线: '#E7E9ED',
  高: '#E95454',
  中: '#FF8A34',
  低: '#FFC423',
};

export const DEFECTS = [
  {
    name: 'Access From',
    type: 'pie',
    radius: ['40%', '70%'],
    avoidLabelOverlap: false,
    label: {
      show: false,
      position: 'center',
    },
    emphasis: {
      label: {
        show: false,
        fontSize: 40,
        fontWeight: 'bold',
      },
    },
    labelLine: {
      show: false,
    },
    data: [
      { value: 1048, name: '超危' },
      { value: 735, name: '高危' },
      { value: 580, name: '中危' },
      { value: 484, name: '低危' },
      { value: 300, name: '建议' },
    ],
  },
];
export const APPLICATION = [
  {
    type: 'pie',
    radius: ['45%', '70%'],
    avoidLabelOverlap: false,
    label: {
      show: false,
      position: 'center',
    },
    itemStyle: {
      borderRadius: 2,
    },
    padAngle: 5,
    emphasis: {
      label: {
        show: false,
        fontSize: 40,
        fontWeight: 'bold',
      },
    },
    labelLine: {
      show: false,
    },
    data: [
      { value: 1048, name: '超危' },
      { value: 735, name: '高危' },
      { value: 580, name: '中危' },
      { value: 484, name: '低危' },
      { value: 300, name: '无风险' },
    ],
  },
];
export const LEAK = cloneDeep(APPLICATION).map((item) => {
  item['data'].map((ite) => {
    ite['value'] = Math.ceil(Math.random() * 100 + 200);
    return ite;
  });
  return item;
});
export const PERMISSION = cloneDeep(APPLICATION).map((item) => {
  item['data'].map((ite) => {
    ite['value'] = Math.ceil(Math.random() * 100 + 200);
    return ite;
  });
  return item;
});
export const CODELIST = [
  '文件数',
  '可执行代码行数',
  '代码注释行数 ',
  '空白行数',
].map((item, index) => {
  let icon = [
    'icon-baogao',
    'icon-yichanghuanjingbianliang',
    'icon-yunpingtai',
    'icon-yunhangzhuangtai',
  ];
  return {
    num: Mock.Random.integer(1, 100),
    label: item,
    icon: icon[index],
  };
});

export const PolicyInfoData: any = {
  创建人: 'admin',
  创建时间: '2021-12-10 12:45:56',
  更新人: 'Default',
  更新时间: '2022-03-10 12:45:56',
  生效范围:
    '集群1，集群2，集群3，集群4，集群5,集群6、集群7、集群8,集群9、集群10,集群11',
  备注: '国家主席习近平6月16日晚同塔吉克斯坦总统拉赫蒙通电话。拉赫蒙表示，在你坚强领导下，中国抗击新冠肺炎疫情取得显著成效，经济社会发展不断取得成功，体现了中国政府出色的治理能力。',
};
export const PolicyDescription = keys(PolicyInfoData).map((item) => {
  return {
    label: item,
    desc: PolicyInfoData[item],
    span: ['生效范围', '备注'].includes(item) ? 2 : 1,
  };
});
export const Code: any = {
  语言: 'Java',
  文件数: '84',
  可执行代码行数: '12712',
  代码注释行数: '7418',
  空白行数: '3021',
};
export const ProjectCode = keys(Code).map((item) => {
  return {
    label: item,
    desc: Code[item],
  };
});

export const IMAGESVIEW = [
  {
    type: 'pie',
    radius: ['45%', '70%'],
    avoidLabelOverlap: false,
    label: {
      show: false,
      position: 'center',
    },
    itemStyle: {
      borderRadius: 2,
    },
    padAngle: 5,
    emphasis: {
      label: {
        show: false,
        fontSize: 40,
        fontWeight: 'bold',
      },
    },
    labelLine: {
      show: false,
    },
    data: [
      { value: 1048, name: '在线' },
      { value: 735, name: '离线' },
    ],
  },
];
export const SECURITYPROFILE = [
  '存在漏洞的镜像',
  '存在异常环境变量的镜像',
  '存在敏感文件的镜像',
  '非可信镜像',
  '存在木马病毒的镜像',
  '存在不允许的软件许可的镜像',
  '存在 WebShell 的镜像',
  '存在风险许可文件引用的镜像',
  '存在不合规软件的镜像',
  'root 用户启动',
].map((item) => {
  return {
    label: item,
    value: Mock.Random.integer(1, 100),
  };
});
export const ProjectInfoData: any = {
  项目类型: 'GIT',
  仓库: 'harborv2(https://harbor.tensorsecurity.com)',
  创建人: 'admin',
  项目标签: 'admin',
  创建时间: '2021-12-10 12:45:56',
  更新人: 'Default',
  更新时间: '2022-03-10 12:45:56',
  项目描述:
    '国家主席习近平6月16日晚同塔吉克斯坦总统拉赫蒙通电话。拉赫蒙表示，在你坚强领导下，中国抗击新冠肺炎疫情取得显著成效，经济社会发展不断取得成功，体现了中国政府出色的治理能力。',
};
export const ProjectDescription = keys(ProjectInfoData).map((item) => {
  return {
    label: item,
    desc: ProjectInfoData[item],
  };
});

export const ProjectDataSource = [
  {
    id: 1,
    项目名称: 'demo_test',
    风险等级: '中',
    项目类型: 'GIT',
    项目标签: 'LeftShift',
    仓库: 'harborv2(https://harbor.tensorsecurity.com)',
    创建人: 'admin',
    创建时间: '2024-09-20 15:44:32',
    更新时间: '2024-09-20 15:44:32',
    项目描述: '这是一个演示项目，用于展示云原生安全左移的概念和实践。',
  },
  {
    id: 2,
    项目名称: 'ScanConnector',
    风险等级: '低',
    项目类型: 'GIT',
    项目标签: 'ResultAggregation',
    仓库: 'harborv2(https://harbor.tensorsecurity.com)',
    创建人: 'admin',
    创建时间: '2024-09-15 11:22:45',
    更新时间: '2024-09-15 11:22:45',
    项目描述: '连接不同扫描工具的结果，实现统一的安全报告。',
  },
  {
    id: 3,
    项目名称: 'SecuRelate',
    风险等级: '高',
    项目类型: 'GIT',
    项目标签: 'SecurityIntegration',
    仓库: 'harborv2(https://harbor.tensorsecurity.com)',
    创建人: 'admin',
    创建时间: '2024-09-10 09:11:22',
    更新时间: '2024-09-10 09:11:22',
    项目描述: '集成多种安全工具，提供全面的安全解决方案。',
  },
  {
    id: 4,
    项目名称: 'RiskRelay',
    风险等级: '高',
    项目类型: 'GIT',
    项目标签: 'RiskAssessment',
    仓库: 'harborv2(https://harbor.tensorsecurity.com)',
    创建人: 'admin',
    创建时间: '2024-08-25 16:34:10',
    更新时间: '2024-08-25 16:34:10',
    项目描述: '评估和管理项目中的风险，提供详细的报告和建议。',
  },
  {
    id: 5,
    项目名称: 'AuditLink',
    风险等级: '中',
    项目类型: 'GIT',
    项目标签: 'ComplianceChecking',
    仓库: 'harborv2(https://harbor.tensorsecurity.com)',
    创建人: 'admin',
    创建时间: '2024-08-10 13:55:33',
    更新时间: '2024-08-10 13:55:33',
    项目描述: '进行合规性检查，确保项目符合安全标准。',
  },
  {
    id: 6,
    项目名称: 'CodeChain',
    风险等级: '中',
    项目类型: 'GIT',
    项目标签: 'CodeToImage',
    仓库: 'harborv2(https://harbor.tensorsecurity.com)',
    创建人: 'admin',
    创建时间: '2024-07-28 10:11:55',
    更新时间: '2024-07-28 10:11:55',
    项目描述: '从源代码到镜像的全链路安全检查。',
  },
  {
    id: 7,
    项目名称: 'CompScan',
    风险等级: '低',
    项目类型: 'GIT',
    项目标签: 'ComponentAnalysis',
    仓库: 'harborv2(https://harbor.tensorsecurity.com)',
    创建人: 'admin',
    创建时间: '2024-07-15 08:00:44',
    更新时间: '2024-07-15 08:00:44',
    项目描述: '开源组件的安全分析和漏洞检测。',
  },
  {
    id: 8,
    项目名称: 'PolicySync',
    风险等级: '中',
    项目类型: 'GIT',
    项目标签: 'PolicyEnforcement',
    仓库: 'harborv2(https://harbor.tensorsecurity.com)',
    创建人: 'admin',
    创建时间: '2024-06-30 14:22:11',
    更新时间: '2024-06-30 14:22:11',
    项目描述: '实施和管理安全策略，确保项目符合安全规范。',
  },
  {
    id: 9,
    项目名称: 'RunSafe',
    风险等级: '高',
    项目类型: 'GIT',
    项目标签: 'RuntimeProtection',
    仓库: 'harborv2(https://harbor.tensorsecurity.com)',
    创建人: 'admin',
    创建时间: '2024-06-15 12:33:22',
    更新时间: '2024-06-15 12:33:22',
    项目描述: '运行时安全保护，防止运行时攻击。',
  },
  {
    id: 10,
    项目名称: 'ImageInsight',
    风险等级: '低',
    项目类型: 'GIT',
    项目标签: 'ImageInspection',
    仓库: 'harborv2(https://harbor.tensorsecurity.com)',
    创建人: 'admin',
    创建时间: '2024-05-30 11:44:33',
    更新时间: '2024-05-30 11:44:33',
    项目描述: '容器镜像的安全检查和分析。',
  },
  {
    id: 11,
    项目名称: 'DevSecOpsBridge',
    风险等级: '中',
    项目类型: 'GIT',
    项目标签: 'DevSecOpsIntegration',
    仓库: 'harborv2(https://harbor.tensorsecurity.com)',
    创建人: 'admin',
    创建时间: '2024-05-10 09:55:11',
    更新时间: '2024-05-10 09:55:11',
    项目描述: '集成DevSecOps流程，提高开发和安全的协同效率。',
  },
];

export const vuln = [
  'CVE-2022-1650',
  'CVE-2019-19919',
  'CVE-2020-36632',
  'CVE-2020-12265',
  'CVE-2019-12900',
  'CVE-2021-23358',
  'CVE-2021-23369',
  'CVE-2022-37434',
  'CVE-2021-3520',
  'CVE-2017-16042',
  'CVE-2020-36632',
  'CVE-2019-19919',
  'CVE-2019-12900',
  'CVE-2021-35942',
  'CVE-2022-23218',
  'CVE-2021-3520',
  'CVE-2022-1650',
  'CVE-2022-37601',
  'CVE-2021-23369',
  'CVE-2021-23358',
  'CVE-2020-12265',
  'CVE-2017-18342',
  'CVE-2021-33574',
  'CVE-2022-23219',
  'CVE-2023-41419',
  'CVE-2019-8457',
  'CVE-2021-23369',
  'CVE-2021-46848',
  'CVE-2019-10744',
  'CVE-2022-1650',
  'CVE-2017-7658',
  'CVE-2021-35942',
  'CVE-2020-28502',
  'CVE-2020-12265',
  'CVE-2020-1747',
  'CVE-2019-12900',
  'CVE-2022-32207',
  'CVE-2017-18342',
  'CVE-2023-41419',
  'CVE-2022-2068',
  'CVE-2022-0686',
  'CVE-2022-2421',
  'CVE-2023-45871',
  'CVE-2019-12900',
  'CVE-2017-12424',
  'CVE-2022-23218',
  'CVE-2020-28502',
  'CVE-2021-44906',
  'CVE-2019-8457',
  'CVE-2020-35527',
  'CVE-2023-1667',
  'CVE-2023-2283',
  'CVE-2023-25173',
  'CVE-2021-41103',
  'CVE-2021-32760',
  'CVE-2022-23471',
  'CVE-2022-31030',
  'CVE-2023-25153',
  'CVE-2023-28842',
  'CVE-2020-10735',
  'CVE-2022-21499',
  'CVE-2023-31436',
  'CVE-2016-2779',
  'CVE-2019-11477',
  'CVE-2017-7656',
  'CVE-2022-1271',
  'CVE-2022-0624',
  'CVE-2021-3600',
  'CVE-2019-3843',
];

export const file = [
  '/WebGoat5.0.22/JavaSource/org/owasp/webgoat/lessons/StoredXss.java的224行',
  '/MyApp1.0/src/main/java/com/example/myapp/controllers/UserController.java的150行',
  '/ProjectA/v1.2/src/com/projecta/security/Filters.java的89行',
  '/ProjectB/v2.0/src/main/java/com/projectb/services/AuthenticationService.java的123行',
  '/AppC/3.1.0/src/main/java/com/appc/handlers/RequestHandler.java的45行',
  '/FrameworkD/2.5.0/src/main/java/com/frameworkd/utils/StringUtils.java的78行',
  '/ServiceE/1.0.0/src/main/java/com/servicee/controllers/ApiGateway.java的102行',
  '/LibraryF/1.1.0/src/main/java/com/libraryf/security/CsrfTokenManager.java的67行',
  '/SystemG/4.0.1/src/main/java/com/systemg/filters/SecurityFilter.java的34行',
  '/ModuleH/2.2.0/src/main/java/com/moduleh/services/DataService.java的56行',
];

export const apName = [
  'diablo-master1_1730105814',
  'diablo-master2_1730105815',
  'diablo-master3_1730105816',
  'diablo-master4_1730105817',
  'diablo-master5_1730105818',
];
export const apType = ['本地上传', '个人应用'];

export const apZuJian = [
  'com.fasterxml.jackson.core/jackson-databind',
  'org.apache.tomcat.embed/tomcat-embed-core',
  'org.yaml/snakeyaml',
  'org.springframework.security/spring-security-core',
  'org.springframework/spring-web',
  'ch.qos.logback/logback-core',
  'ch.qos.logback/logback-classic',
  'org.springframework/spring-core',
  'com.google.guava/guava',
  'org.hibernate/hibernate-validator',
  'org.springframework.boot/spring-boot',
  'org.springframework.security/spring-security-web',
  'org.springframework/spring-expression',
  'com.github.kevinsawicki/http-request',
  'org.hamcrest/hamcrest-library',
  'com.fasterxml.jackson.core/jackson-annotations',
  'com.fasterxml.jackson.core/jackson-core',
  'org.jboss.logging/jboss-logging',
  'org.slf4j/jcl-over-slf4j',
  'redis.clients/jedis',
  'com.samskivert/jmustache',
];

export const vulnType = ['系统漏洞', '应用漏洞'];
export const vulnBH = [
  'CWE-79',
  'CWE-89',
  'CWE-22',
  'CWE-352',
  'CWE-319',
  'CWE-78',
  'CWE-200',
  'CWE-20',
  'CWE-347',
  'CWE-287',
  'CWE-434',
  'CWE-502',
  'CWE-338',
  'CWE-732',
  'CWE-269',
  'CWE-400',
  'CWE-611',
  'CWE-476',
  'CWE-918',
  'CWE-798',
];
export const vulnDesc = [
  "Improper Neutralization of Input During Web Page Generation ('Cross-site Scripting')",
  "Improper Neutralization of Special Elements used in an SQL Command ('SQL Injection')",
  "Improper Limitation of a Pathname to a Restricted Directory ('Path Traversal')",
  'Cross-Site Request Forgery (CSRF)',
  'Cleartext Transmission of Sensitive Information',
  "Improper Neutralization of Special Elements used in an OS Command ('OS Command Injection')",
  'Information Exposure',
  'Input Validation Error',
  'Use of Untrusted Cryptographic Primitives',
  'Improper Authentication',
];
export const xkqc = [
  'MIT License',
  'GNU General Public License v3.0',
  'GNU General Public License v2.0',
  'GNU Lesser General Public License v3.0',
  'GNU Lesser General Public License v2.1',
  'Apache License 2.0',
  'BSD 2-Clause Simplified License',
  'BSD 3-Clause New or Revised License',
  'Mozilla Public License 2.0',
  'Creative Commons Zero v1.0 Universal',
  'Creative Commons Attribution 4.0',
  'Creative Commons Attribution Share Alike 4.0',
  'Eclipse Public License 2.0',
  'GNU Affero General Public License v3.0',
  'ISC License',
  'Artistic License 2.0',
  'zlib License',
  'The Unlicense',
  'Common Development and Distribution License 1.1',
  'University of Illinois/NCSA Open Source License',
  'Mozilla Public License 1.1',
  'GNU Free Documentation License v1.3',
  'GNU Affero General Public License v3.0',
  'GNU Lesser General Public License v2.1',
  'GNU General Public License v2.0',
  'GNU General Public License v3.0',
  'Open Software License 3.0',
  'Simplified BSD License',
  'Educational Community License v2.0',
  'Do What The F*ck You Want To Public License',
];
export const images = [
  'tensorsecurity/node-image:testcn-1.0',
  'tensorsecurity/node-image:testcn-2.0',
  'tensorsecurity/node-image:testcn-3.0',
  'tensorsecurity/node-image:testcn-4.0',
  'tensorsecurity/node-image:testcn-5.0',
  'tensorsecurity/node-image:testcn-6.0',
  'tensorsecurity/node-image:testcn-7.0',
  'tensorsecurity/node-image:testcn-8.0',
  'tensorsecurity/node-image:testcn-9.0',
  'tensorsecurity/node-image:testcn-10.0',
];
export const PolicyData = [
  {
    策略名称: 'demo_policy',
    仓库生效范围: '.*',
    标签生效范围: ['LeftShift'],
    创建人: 'admin',
    创建时间: '2024-09-20 15:44:32',
    更新人: 'admin',
    更新时间: '2024-09-20 15:44:32',
    备注: '演示策略，用于测试和验证',
  },
  {
    策略名称: 'CodeScan',
    仓库生效范围: 'code-repos/.*',
    标签生效范围: ['CodeToImage'],
    创建人: 'admin',
    创建时间: '2024-09-15 11:22:45',
    更新人: 'admin',
    更新时间: '2024-09-15 11:22:45',
    备注: '确保代码质量',
  },
  {
    策略名称: 'ImageScan',
    仓库生效范围: 'image-repos/.*',
    标签生效范围: ['ImageInspection'],
    创建人: 'admin',
    创建时间: '2024-09-10 09:11:22',
    更新人: 'admin',
    更新时间: '2024-09-10 09:11:22',
    备注: '确保镜像安全',
  },
  {
    策略名称: 'ComponentAnalysis',
    仓库生效范围: 'component-repos/.*',
    标签生效范围: ['ComponentAnalysis'],
    创建人: 'admin',
    创建时间: '2024-08-25 16:34:10',
    更新人: 'admin',
    更新时间: '2024-08-25 16:34:10',
    备注: '检测开源组件漏洞',
  },
  {
    策略名称: 'ComplianceCheck',
    仓库生效范围: 'compliance-repos/.*',
    标签生效范围: ['ComplianceChecking'],
    创建人: 'admin',
    创建时间: '2024-08-10 13:55:33',
    更新人: 'admin',
    更新时间: '2024-08-10 13:55:33',
    备注: '确保项目符合安全标准',
  },
  {
    策略名称: '代码扫描策略',
    仓库生效范围: 'code-repos/.*',
    标签生效范围: ['CodeToImage', 'ResultAggregation'],
    创建人: 'admin',
    创建时间: '2024-07-28 10:11:55',
    更新人: 'admin',
    更新时间: '2024-07-28 10:11:55',
    备注: '确保代码质量',
  },
  {
    策略名称: '镜像扫描策略',
    仓库生效范围: 'image-repos/.*',
    标签生效范围: ['ImageInspection', 'SecurityIntegration'],
    创建人: 'admin',
    创建时间: '2024-07-15 08:00:44',
    更新人: 'admin',
    更新时间: '2024-07-15 08:00:44',
    备注: '确保镜像安全',
  },
  {
    策略名称: '组件分析策略',
    仓库生效范围: 'component-repos/.*',
    标签生效范围: ['ComponentAnalysis', 'RiskAssessment'],
    创建人: 'admin',
    创建时间: '2024-06-30 14:22:11',
    更新人: 'admin',
    更新时间: '2024-06-30 14:22:11',
    备注: '检测开源组件漏洞',
  },
  {
    策略名称: '合规性检查策略',
    仓库生效范围: 'compliance-repos/.*',
    标签生效范围: ['ComplianceChecking', 'PolicyEnforcement'],
    创建人: 'admin',
    创建时间: '2024-06-15 12:33:22',
    更新人: 'admin',
    更新时间: '2024-06-15 12:33:22',
    备注: '确保项目符合安全标准',
  },
  {
    策略名称: '运行时保护策略',
    仓库生效范围: 'runtime-repos/.*',
    标签生效范围: ['RuntimeProtection', 'SecurityIntegration'],
    创建人: 'admin',
    创建时间: '2024-05-30 11:44:33',
    更新人: 'admin',
    更新时间: '2024-05-30 11:44:33',
    备注: '防止运行时攻击',
  },
  {
    策略名称: '安全集成策略',
    仓库生效范围: 'security-repos/.*',
    标签生效范围: ['SecurityIntegration', 'LeftShift'],
    创建人: 'admin',
    创建时间: '2024-05-10 09:55:11',
    更新人: 'admin',
    更新时间: '2024-05-10 09:55:11',
    备注: '整合多种安全工具',
  },
  {
    策略名称: 'DevSecOps集成策略',
    仓库生效范围: 'devsecops-repos/.*',
    标签生效范围: ['DevSecOpsIntegration', 'CodeToImage'],
    创建人: 'admin',
    创建时间: '2024-04-20 10:00:00',
    更新人: 'admin',
    更新时间: '2024-04-20 10:00:00',
    备注: '提高开发和安全的协同效率',
  },
].map((item, index) => ({ ...item, id: index }));

export const qxmc = [
  'J2EE不正确的访问权限控制',
  'HTTP参数污染',
  'HTML5过于宽泛的消息发布策略',
  'HTML5过于宽泛的CORS策略',
  'Hadoop提交的Job可被篡改',
  '允许对Hadoop集群恶意操纵',
  '允许对Hadoop集群恶意操纵',
  'Android片段注入',
  'CSV公式注入',
  'Flex开启Debug调试模式',
  '文件权限操纵',
  'Spring Webflow文件泄露',
  'Spring文件泄露',
  '基于文件的跨区域脚本攻击',
  'SpEL表达式注入',
  'EJB使用JavaIO包',
  'EJB使用类加载器',
  'XMLDecoder注入',
  '不安全的YAML反序列化',
  'Struts2动态方法调用未禁用',
  '系统信息泄露',
  'J2EE缺少安全角色配置',
  'J2EE缺少servlet映射',
  'J2EE不安全的实体Bean远程声明',
  'JavaScript劫持',
  '加密密钥为空',
  'HMAC密钥为空',
  '硬编码加密密钥',
  '加密密钥为NULL',
  '日志伪造',
  'IMAP命令注入',
  'POP3命令注入',
  'SMTP命令注入',
  '使用不安全的绑定器配置',
  '不应将请求参数绑定到持久化对象中',
];
export const fxdj = ['超危', '高危', '中危', '低危'];
export const gzmj = [
  '禁止使用过期的组件',
  '禁止使用已知的弱加密算法组件',
  '禁止使用已知的弱随机数生成器组件',
  '禁止使用已知的弱哈希函数组件',
  '禁止使用已知的弱密钥长度组件',
  '禁止使用已知的弱证书组件',
  '禁止使用已知的弱密码策略组件',
  '禁止使用已知的弱身份验证机制组件',
  '禁止使用已知的弱会话管理机制组件',
  '禁止使用已知的弱输入验证机制组件',
  '禁止使用已知的弱输出编码机制组件',
  '禁止使用已知的弱日志记录机制组件',
  '禁止使用已知的弱错误处理机制组件',
  '禁止使用已知的弱文件操作机制组件',
  '禁止使用已知的弱网络通信机制组件',
  '禁止使用已知的弱数据库连接组件',
  '禁止使用已知的弱缓存机制组件',
  '禁止使用已知的弱API调用组件',
  '禁止使用已知的弱Web框架组件',
  '禁止使用已知的弱前端库组件',
  '禁止使用已知的弱后端服务组件',
  '禁止使用已知的弱中间件组件',
  '禁止使用已知的弱消息队列组件',
  '禁止使用已知的弱任务调度组件',
  '禁止使用已知的弱容器管理组件',
  '禁止使用已知的弱配置管理组件',
  '禁止使用已知的弱日志分析组件',
  '禁止使用已知的弱性能监控组件',
  '禁止使用已知的弱安全审计组件',
  '禁止使用已知的弱权限管理组件',
  '禁止使用已知的弱数据同步组件',
  '禁止使用已知的弱数据备份组件',
  '禁止使用已知的弱数据恢复组件',
  '禁止使用已知的弱数据加密组件',
  '禁止使用已知的弱数据解密组件',
  '禁止使用已知的弱数据压缩组件',
  '禁止使用已知的弱数据解压组件',
  '禁止使用已知的弱数据传输组件',
  '禁止使用已知的弱数据存储组件',
  '禁止使用已知的弱数据检索组件',
  '禁止使用已知的弱数据分析组件',
  '禁止使用已知的弱数据可视化组件',
  '禁止使用已知的弱用户界面组件',
  '禁止使用已知的弱用户交互组件',
  '禁止使用已知的弱用户认证组件',
  '禁止使用已知的弱用户授权组件',
  '禁止使用已知的弱用户管理组件',
];
export const gzms = [
  '确保项目中使用的开源组件都是最新的，避免使用已知存在严重漏洞的组件，以减少安全风险。',
  '确保项目中使用的加密算法组件是安全的，避免使用已知的弱加密算法组件，以保护数据的安全性和隐私。',
  '确保项目中使用的随机数生成器组件是强随机数生成器，避免使用已知的弱随机数生成器组件，以保护数据的安全性。',
  '确保项目中使用的哈希函数组件是强哈希函数，避免使用已知的弱哈希函数组件，以保护数据的安全性。',
  '确保项目中使用的密钥长度组件足够强，避免使用已知的弱密钥长度组件，以保护数据的安全性。',
  '确保项目中使用的证书组件是强证书，避免使用已知的弱证书组件，以保护数据的安全性。',
  '确保项目中使用的密码策略组件是强密码策略，避免使用已知的弱密码策略组件，以保护数据的安全性。',
  '确保项目中使用的是强身份验证机制组件，避免使用已知的弱身份验证机制组件，以保护数据的安全性。',
  '确保项目中使用的是强会话管理机制组件，避免使用已知的弱会话管理机制组件，以保护数据的安全性。',
  '确保项目中使用的是强输入验证机制组件，避免使用已知的弱输入验证机制组件，以保护数据的安全性。',
  '确保项目中使用的是强输出编码机制组件，避免使用已知的弱输出编码机制组件，以保护数据的安全性。',
  '确保项目中使用的是强日志记录机制组件，避免使用已知的弱日志记录机制组件，以保护数据的安全性。',
  '确保项目中使用的是强错误处理机制组件，避免使用已知的弱错误处理机制组件，以保护数据的安全性。',
  '确保项目中使用的是强文件操作机制组件，避免使用已知的弱文件操作机制组件，以保护数据的安全性。',
  '确保项目中使用的是强网络通信机制组件，避免使用已知的弱网络通信机制组件，以保护数据的安全性。',
  '确保项目中使用的数据库连接组件是强数据库连接组件，避免使用已知的弱数据库连接组件，以保护数据的安全性。',
  '确保项目中使用的缓存机制组件是强缓存机制组件，避免使用已知的弱缓存机制组件，以保护数据的安全性。',
  '确保项目中使用的API调用组件是强API调用组件，避免使用已知的弱API调用组件，以保护数据的安全性。',
  '确保项目中使用的Web框架组件是强Web框架组件，避免使用已知的弱Web框架组件，以保护数据的安全性。',
  '确保项目中使用的前端库组件是强前端库组件，避免使用已知的弱前端库组件，以保护数据的安全性。',
  '确保项目中使用的后端服务组件是强后端服务组件，避免使用已知的弱后端服务组件，以保护数据的安全性。',
  '确保项目中使用的中间件组件是强中间件组件，避免使用已知的弱中间件组件，以保护数据的安全性。',
  '确保项目中使用的消息队列组件是强消息队列组件，避免使用已知的弱消息队列组件，以保护数据的安全性。',
  '确保项目中使用的任务调度组件是强任务调度组件，避免使用已知的弱任务调度组件，以保护数据的安全性。',
  '确保项目中使用的容器管理组件是强容器管理组件，避免使用已知的弱容器管理组件，以保护数据的安全性。',
  '确保项目中使用的配置管理组件是强配置管理组件，避免使用已知的弱配置管理组件，以保护数据的安全性。',
  '确保项目中使用的日志分析组件是强日志分析组件，避免使用已知的弱日志分析组件，以保护数据的安全性。',
  '确保项目中使用的性能监控组件是强性能监控组件，避免使用已知的弱性能监控组件，以保护数据的安全性。',
  '确保项目中使用的是强安全审计组件，避免使用已知的弱安全审计组件，以保护数据的安全性。',
  '确保项目中使用的权限管理组件是强权限管理组件，避免使用已知的弱权限管理组件，以保护数据的安全性。',
  '确保项目中使用的数据同步组件是强数据同步组件，避免使用已知的弱数据同步组件，以保护数据的安全性。',
  '确保项目中使用的数据备份组件是强数据备份组件，避免使用已知的弱数据备份组件，以保护数据的安全性。',
  '确保项目中使用的数据恢复组件是强数据恢复组件，避免使用已知的弱数据恢复组件，以保护数据的安全性。',
  '确保项目中使用的数据加密组件是强数据加密组件，避免使用已知的弱数据加密组件，以保护数据的安全性。',
  '确保项目中使用的数据解密组件是强数据解密组件，避免使用已知的弱数据解密组件，以保护数据的安全性。',
  '确保项目中使用的数据压缩组件是强数据压缩组件，避免使用已知的弱数据压缩组件，以保护数据的安全性。',
  '确保项目中使用的数据解压组件是强数据解压组件，避免使用已知的弱数据解压组件，以保护数据的安全性。',
  '确保项目中使用的数据传输组件是强数据传输组件，避免使用已知的弱数据传输组件，以保护数据的安全性。',
  '确保项目中使用的数据存储组件是强数据存储组件，避免使用已知的弱数据存储组件，以保护数据的安全性。',
  '确保项目中使用的数据检索组件是强数据检索组件，避免使用已知的弱数据检索组件，以保护数据的安全性。',
  '确保项目中使用的数据分析组件是强数据分析组件，避免使用已知的弱数据分析组件，以保护数据的安全性。',
  '确保项目中使用的数据可视化组件是强数据可视化组件，避免使用已知的弱数据可视化组件，以保护数据的安全性。',
  '确保项目中使用的用户界面组件是强用户界面组件，避免使用已知的弱用户界面组件，以保护数据的安全性。',
  '确保项目中使用的用户交互组件是强用户交互组件，避免使用已知的弱用户交互组件，以保护数据的安全性。',
  '确保项目中使用的用户认证组件是强用户认证组件，避免使用已知的弱用户认证组件，以保护数据的安全性。',
  '确保项目中使用的用户授权组件是强用户授权组件，避免使用已知的弱用户授权组件，以保护数据的安全性。',
  '确保项目中使用的用户管理组件是强用户管理组件，避免使用已知的弱用户管理组件，以保护数据的安全性。',
];
